### ISSUE TITLE
"CheckNonceGUI is damaged and cannot be opened"

### ISSUE THREAD

**Issue by Samgisaninja** [MatthewPierson/CheckNonceGUI#2]
macOS 10.15.1, MacBookPro13,2

**Comment by Samgisaninja** [comment]
only affects version 0.6.0

**Comment by MatthewPierson** [comment]
Does running "xattr -cr /Applications/CheckNonceGUI.app" fix it?

**Comment by Samgisaninja** [comment]
yes

**Comment by Samgisaninja** [comment]
my apologies, I am too lazy to read READMEs :/

**Comment by MatthewPierson** [comment]
No worries! Glad its working now
