### ISSUE TITLE
cannot enter PWNDFU Mode

### ISSUE THREAD

**Issue by cidmex** [MatthewPierson/CheckNonceGUI#3]
I have tried 200+ times to put my device into DFU mode to enter PWNDFU Mode through your application but none of my attempts succeeded.Most of time after it failed,my device would not reboot automatically.
iPhone6,2|MacOS Catalina 10.15.1
<img width="1057" alt="sc" src="https://user-images.githubusercontent.com/54629426/68540251-9ddc6d00-03c9-11ea-85e7-c18367d4fedb.png">

**Comment by MatthewPierson** [comment]
I wouldn't recommend 10.15.1 , it breaks a lot of things. "Device has no langid" is a ipwndfu issue, google around for how to fix that

**Comment by cidmex** [comment]
Thanks for your help! It seems to be a problem with libusb and I successfully set the nonce on my 5s after solving that. I found a strange problem that when I was using the CheckNonceGUI or the current version of checkm8 nonce setter it said that either unsupported device or no device found (My device is iPad7,5) but in the previous version of checkm8 nonce setter I entered my device model manually and everything went well,it just worked.
<img width="904" alt="截屏2019-11-1020 10 10" src="https://user-images.githubusercontent.com/54629426/68544653-6341f700-0400-11ea-87fd-6f1a65f303a3.png">
<img width="734" alt="截屏2019-11-1021 01 44" src="https://user-images.githubusercontent.com/54629426/68544657-69d06e80-0400-11ea-8472-a3c2c897c9c4.png">

**Comment by MatthewPierson** [comment]
Ah, I somehow removed support for some devices by mistake! Will fix that now sorry

**Comment by MatthewPierson** [comment]
Just updated the app to fix this issue, check the releases tab for the .app! Thank you for bringing it to my attention! Please let me know if the update fixes it or not

**Comment by cidmex** [comment]
It worked! Thanks!
