### ISSUE TITLE
cant compile "No such module "SwiftShell"

### ISSUE THREAD

**Issue by zunda-pixel** [MatthewPierson/CheckNonceGUI#5]
I have a Error "No such module "SwiftShell"
macOS Mojave 10.14.6
Xcode Latest
<img width="1920" alt="Screen Shot 2020-02-10 at 4 07 03" src="https://user-images.githubusercontent.com/47569369/74108170-d18e8500-4bba-11ea-98a6-f147916dc7b3.png">

**Comment by zunda-pixel** [comment]
I open parent Folder
I can success to compile

**Comment by dony71** [comment]
@zunda-pixel : I have same problem and I don't understand what you mean with parent folder? can you explain more detail?
